### ISSUE TITLE
Is Windows N Edition supported?

### ISSUE THREAD

**Issue by pedropombeiro** [MicrosoftDX/MicrosoftHLSSDK#12]
I just got this error while registering the plugin on Windows 10 N. Is it not supported on N Edition?

```
2015-11-13 11:05:22:7556 [6] WARNING - [Task`1] - Unobserved FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Microsoft.HLSClient.HLSControllerFactory..ctor()
   at Microsoft.PlayerFramework.Adaptive.HLS.HLSPlugin..ctor()
```

**Comment by jitghosh** [comment]
Hi:

Windows N does not include the media stack - i.e. Media Foundation. Since the HLS SDK is built on top of MF - it is not supported on Windows N.

-Jit
